spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datajpa?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  output:
    ansi:
      enabled: always
  sql:
    init:
      encoding: UTF-8

logging.level:
  org.hibernate.SQL: debug
